### ISSUE TITLE
Unable to install the External-K8s-Secret from the Helm Chart 

### ISSUE THREAD

**Issue by sudarshntn** [godaddy/kubernetes-external-secrets#365] opened 2020-04-30 18:55 UTC
When I tried to deploy the helm chart of the External-k8s-secret I am getting below error:

Kubernetes version: 1.15.11
Helm Version: 
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}

Commands executed:
helm repo add external-secrets https://godaddy.github.io/kubernetes-external-secrets/
"external-secrets" has been added to your repositories

helm install external-secrets/kubernetes-external-secrets --name my-release
Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by Flydiverny** [comment] 2020-04-30 19:16
@sudarshntn Doesn't look KES related, have you checked this helm issue https://github.com/helm/helm/issues/6361 ?

**Comment by sudarshntn** [comment] 2020-04-30 19:39
@Flydiverny Can I use Helm3 to deploy KES or we have to use Helm2?

**Comment by Flydiverny** [comment] 2020-04-30 19:48
@sudarshntn You can try Helm 3, but helm 2 is what have been tested.

**Comment by sudarshntn** [comment] 2020-04-30 19:51
With latest Helm 3.2.0 it worked but currently not working with either Helm 3.1.1 or Helm 2.x version.

**Comment by Flydiverny** [comment] 2020-05-01 01:01
Cannot reproduce the issue with the same versions as posted in the initial issue.

```
~/Code/test/darwin-amd64 (⎈ |minikube:default)
λ minikube start --kubernetes-version=1.15.11
🔥  Deleting "minikube" in hyperkit ...
💀  Removed all traces of the "minikube" cluster.
😄  minikube v1.9.2 on Darwin 10.15
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node m01 in cluster minikube
💾  Downloading Kubernetes v1.15.11 preload ...
    > preloaded-images-k8s-v2-v1.15.11-docker-overlay2-amd64.tar.lz4: 517.92 Mi
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.11 on Docker 19.03.8 ...
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

❗  /usr/local/bin/kubectl is v1.18.2, which may be incompatible with Kubernetes v1.15.11.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version

~/Code/test/darwin-amd64 (⎈ |minikube:default)
λ ./helm init
$HELM_HOME has been configured at /Users/flydiverny/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation

~/Code/test/darwin-amd64 (⎈ |minikube:default)
λ ./helm install external-secrets/kubernetes-external-secrets --name my-release
NAME:   my-release
LAST DEPLOYED: Fri May  1 02:56:27 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                                    AGE
my-release-kubernetes-external-secrets  0s

==> v1/Pod(related)
NAME                                                     AGE
my-release-kubernetes-external-secrets-644f98dc7c-4m5bj  0s

==> v1/Service
NAME                                    AGE
my-release-kubernetes-external-secrets  0s

==> v1/ServiceAccount
NAME                                    AGE
my-release-kubernetes-external-secrets  0s

==> v1beta1/ClusterRole
NAME                                    AGE
my-release-kubernetes-external-secrets  0s

==> v1beta1/ClusterRoleBinding
NAME                                         AGE
my-release-kubernetes-external-secrets       0s
my-release-kubernetes-external-secrets-auth  0s


NOTES:
The kubernetes external secrets has been installed. Check its status by running:
  kubectl --namespace default get pods -l "app.kubernetes.io/name=kubernetes-external-secrets,app.kubernetes.io/instance=my-release"

Visit https://github.com/godaddy/kubernetes-external-secrets for instructions on how to use kubernetes external secrets


~/Code/test/darwin-amd64 (⎈ |minikube:default)
λ kubectl version --short
Client Version: v1.18.2
Server Version: v1.15.11

~/Code/test/darwin-amd64 (⎈ |minikube:default)
λ ./helm version
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

Closing this as the chart seems fine. If anyone has similar issues please reopen.

**Closed by Flydiverny** 2020-05-01 01:01 UTC
