### ISSUE TITLE
Not so secure Secrets

### ISSUE THREAD

**Issue by IamViditAgarwal** [godaddy/kubernetes-external-secrets#421] opened 2020-07-07 12:33 UTC
Hi, 
When I heard for the first time about this project, I was excited to try out the project and deploy in my cluster infrastructure to see how the things works in all.
I have few questions to ask related to the security concerns.

- On deploying external-secret into the cluster, using the `kubectl apply -f` command, It basically generates the K8 native secret object. Which means the generated K8 native secret object will be stored in the ETCD cluster in the master node of the K8 cluster. Any attacker will be able to access these secrets. The point of storing and managing the secrets out of the cluster is to make sure that it doesnt lives in the cluster. But in this project, it lives in the cluster and can be viewed and retrieved easily using the `kubectl get secrets`. 

What would I like to know is how to protect that generated secret ? Is there any way we can omit the generation of that native secret and pass the value or data of secret directly to the pod resource.

What i m looking for is the best way of managing the secret in and out of the cluster  as its a security concern to store secret in cluster , as its gets stored in only **base64** encoded form which is not much secure.

Hoping to get answers on this thread.

**Comment by Flydiverny** [comment] 2020-07-07 12:48
Closing this as duplicate of #46 and #81

**Closed by Flydiverny** 2020-07-07 12:48 UTC
