### ISSUE TITLE
no_proxy environment variable is not getting honored

### ISSUE THREAD

**Issue by anshrma** [godaddy/kubernetes-external-secrets#59] opened 2019-05-08 18:34 UTC
Hi - I am mounting environment variables as

```

spec:
      serviceAccountName: kubernetes-external-secrets-service-account
      containers:
        - image: "godaddy/kubernetes-external-secrets:1.2.0"
          imagePullPolicy: Always
          name: kubernetes-external-secrets
          envFrom:
            - configMapRef:
                name: proxy-environment-variables

```

My proxy-environment-variable config map is as follows

```

apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-environment-variables
  namespace: kubernetes-external-secrets
data:
  HTTPS_PROXY: my_redacted_proxy
  HTTP_PROXY: my_redacted_proxy
  http_proxy: my_redacted_proxy
  https_proxy: my_redacted_proxy
  NO_PROXY: my_redacted_no_proxy urls
  no_proxy: my_redacted_no_proxy urls

```

One of the no proxy cidr is 10.100.0.0/16

When i deploy the pod exists with the following message

```
{
    "log": "Error: Failed to get /openapi/v2 and /swagger.json: tunneling socket could not be established, statusCode=503
",
    "stream": "stderr",
    "docker": {
        "container_id": "052ffccfdf5a55a7cc22f58e5f9f01cc5e028804667962810cfc50c6573f9acc"
    },
    "kubernetes": {
        "container_name": "kubernetes-external-secrets",
        "namespace_name": "kubernetes-external-secrets",
        "pod_name": "kubernetes-external-secrets-775d45f74d-bjr55",
        "container_image": "godaddy/kubernetes-external-secrets:1.2.0",
        "container_image_id": "docker-pullable://godaddy/kubernetes-external-secrets@sha256:6439feeef5602ed0bd3fd635f0e403c1274b3198c9a59526c84a3437152ae245",
        "pod_id": "addbacb1-71b7-11e9-b8cb-02ef4f9bf35c",
        "labels": {
            "name": "kubernetes-external-secrets",
            "pod-template-hash": "775d45f74d",
            "service": "kubernetes-external-secrets"
        },
        "host": "ip-172-25-130-225.us-east-2.compute.internal",
        "master_url": "https://10.100.0.1:443/api",
        "namespace_id": "ad7f4034-71b7-11e9-b8cb-02ef4f9bf35c"
    }
}
```

I tail the proxy logs and find that these calls are going over proxy

1557340191.194  59985 172.25.130.225 TAG_NONE/503 0 CONNECT 10.100.0.1:443 - HIER_NONE/- -

**Comment by JacopoDaeli** [comment] 2019-05-19 23:51
@anshrma I am not sure to understand what you are trying to do here. Can you explain better what do you want to achieve with setting `no_proxy` env within the `kubernetes external secrets` controller?

**Comment by JacopoDaeli** [comment] 2019-05-30 21:01
Closing this because no follow up.

**Closed by JacopoDaeli** 2019-05-30 21:01 UTC
Labels: invalid

**Comment by willemm** [comment] 2020-11-30 13:00
We have the same issue.
What we're trying to achieve is for the externalsecrets provider (in our case azure) to go through the proxy.

But this gives the above error about /openapi/v2 and /swagger.json

To fix this, one would expect that adding ".cluster.local" or something similar to no_proxy would solve the issue but it does not.

However, the problem is not that it doesn't honor no_proxy, the problem is that the kubernetes-apiclient software uses the direct IP address of the api server and not the hostname, and no_proxy doesn't support IP ranges.  (Tested by hardcoding the kubernetes API IP adddress in no_proxy).

This is obviously not a real solution as the k8s-api IP address is not fixed.  To really fix this would probably need a step in daemon.js that appends the kubernetes API IP to the no_proxy environment variable or something like that.
